#!/bin/bash

set -e

DERIVED_DATA_PATH=$1
BUNDLE_IDENTIFIER='com.xpier.inputmethod.Xpier'
INSTALL_LOCATION='/Library/Input Methods'

cd "$(dirname $0)"
source common.sh

pkgbuild \
    --root "${PROJECT_ROOT}/${DERIVED_DATA_PATH}/Build/Products/Release" \
    --filter '.*\.swiftmodule$' \
    --component-plist Xpier-component.plist \
    --identifier "${BUNDLE_IDENTIFIER}" \
    --version "$(get_app_version)" \
    --install-location "${INSTALL_LOCATION}" \
    --scripts "${PROJECT_ROOT}/scripts" \
    Xpier-component.pkg

sed "s/@VERSION@/$(get_app_version)/" Distribution > Distribution-versioned.xml

productbuild \
    --distribution Distribution-versioned.xml \
    --package-path . \
    --resources . \
    Xpier.pkg

rm Distribution-versioned.xml

rm Xpier-component.pkg
